-- Import CSV data to db by using a staging table

-- Temporary table for initial CSV data import
CREATE TABLE staging (
	first_col integer,
	result_id integer,
 	race_id integer,
	driver_id integer,
	constructor_id integer,
	car_number integer,
	grid int,
	car_position integer,
	position_text varchar(2),
	position_order integer,
	points float,
	lap integer,
	passing_time varchar(15),
	milliseconds integer,
	fastest_lap integer,
	driver_rank integer,
	fastest_lap_time varchar(15),
	fastest_lap_speed float,
	status_id integer,
	time_year varchar(4),
	round integer,
	circuit_id integer,
	race_name varchar(80),
	time_date date,
	time_of_day time,
	race_url varchar(100),
	fp1_date varchar(50),
	fp1_time varchar(50),
	fp2_date varchar(50),
	fp2_time varchar(50),
	fp3_date varchar(50),
	fp3_time varchar(50),
	quali_date varchar(50),
	quali_time varchar(50),
	sprint_date varchar(50),
	sprint_time varchar(50),
	circuit_ref varchar(20),
	circuit_name varchar(50),
	circuit_location varchar(45),
	country varchar(30),
	latitude float,
	longitude float,
	altitude integer, -- \N?
	circuit_url varchar(100),
	driver_ref varchar(50),
	driver_num integer,
	code char(3),
	forename varchar(30),
	sourname varchar(30),
	dob DATE,
	driver_nationality varchar(30),
	driver_url varchar(100),
	const_ref varchar(50),
	const_name varchar(30),
	const_nationality varchar(30),
	const_url varchar(100),
	lt_lap integer,
	lt_position integer,
	lt_passing_time interval,
	lt_milliseconds integer,
	stop integer,
	ps_lap integer,
	ps_time varchar(20),
	ps_duration interval,
	ps_milliseconds integer,
	driv_stand_id integer,
	ds_points float,
	ds_position integer,
	ds_position_text varchar(2),
	ds_wins integer,
	const_stand_id integer,
	cs_points float,
	cs_position integer,
	cs_position_text varchar(2),
	cs_wins integer,
	status varchar(20)
);

-- Import data from CSV file to staging table
-- Paste the command into psql shell, adjust file path
\COPY staging(first_col, result_id, race_id, driver_id, constructor_id, car_number, grid, car_position, position_text, position_order, points, lap, passing_time, milliseconds, fastest_lap, driver_rank, fastest_lap_time, fastest_lap_speed, status_id, time_year, round, circuit_id, race_name, time_date, time_of_day, race_url, fp1_date, fp1_time, fp2_date, fp2_time, fp3_date, fp3_time, quali_date, quali_time, sprint_date, sprint_time, circuit_ref, circuit_name, circuit_location, country, latitude, longitude, altitude, circuit_url, driver_ref, driver_num, code, forename, sourname, dob, driver_nationality, driver_url, const_ref, const_name, const_nationality, const_url, lt_lap, lt_position, lt_passing_time, lt_milliseconds, stop, ps_lap, ps_time, ps_duration, ps_milliseconds, driv_stand_id, ds_points, ds_position, ds_position_text, ds_wins, const_stand_id, cs_points, cs_position, cs_position_text, cs_wins, status) FROM 'path\to\file' DELIMITER ',' CSV HEADER NULL AS '\N';
